### ISSUE TITLE
Getting -> "TypeError: Object(...) is not a function" on loading angular 5 application

### ISSUE THREAD

**Issue by Tawsif** [stevermeister/ngx-cookie-service#101]
## Expected Behavior
It should load angular 5 application without any error

## Actual Behavior
Throws TypeError: Object(...) is not a function

## Steps to Reproduce the Problem
Install ngxCookieService and try to run application

## Specifications

  - Version: Latest version (^3.0.3)
  - Browser: Chrome
  - Attached Screenshot for the same
![image](https://user-images.githubusercontent.com/6791620/78963437-209e5b00-7b15-11ea-833e-3aa28cdbfefb.png)

**Comment by agarwalaman263** [comment]
Even I am facing the same issue with angular 7

**Comment by Johnny99211** [comment]
Same error here. What have you done to fix this?

**Comment by Tawsif** [comment]
downgraded to version 2.2.4 fixed the issue

**Comment by agarwalaman263** [comment]
> downgraded to version 2.2.4 fixed the issue

It works like magic
Thank you
