### ISSUE TITLE
Getting Error "Uncaught TypeError: Object(...) is not a function     at ngx-cookie-service.js:154"

### ISSUE THREAD

**Issue by JituG22** [stevermeister/ngx-cookie-service#103]
## Expected Behavior
...  ngx-cookie-service

## Actual Behavior
...

## Steps to Reproduce the Problem
... npm i ngx-cookie-service --save 

## Specifications
"is not a function     at ngx-cookie-service.js:154"

  - Version: ... Angular6
  - Browser: ... chrome
  - ...
![issue](https://user-images.githubusercontent.com/16048754/84364932-613a5380-abee-11ea-8e86-87a36e4a6e2b.jpg)

**Comment by JituG22** [comment]
I got install   **"ngx-cookie-service": "^2.1.0",**  which is very old version and now **my issue got fixed**.
However I l still looking forward  ngx-cookie-service new version issue should be  fix.

**Comment by tecfu** [comment]
I also had this issue on "@angular/core": "~7.2.0",

Downgrading to  "ngx-cookie-service": "^2.1.0" worked for me also.
