### ISSUE TITLE
Peer dependencies warning with angular 10

### ISSUE THREAD

**Issue by yallanki-rivet** [stevermeister/ngx-cookie-service#104]
Thanks for the great library !!!

As angular 10 is released, can you please make the library compatible with angular 10. I see the below warning on npm install

**_npm WARN ngx-cookie-service@3.0.4 requires a peer of @angular/common@^9.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-cookie-service@3.0.4 requires a peer of @angular/core@^9.0.5 but none is installed. You must install peer dependencies yourself._**

**Thanks in advance...**

**Comment by Maximaximum** [comment]
@stevermeister could you please give us a hint about when this can be released?

**Comment by kristijanbambir** [comment]
Multiple new versions have been released in the meantime :)

**Comment by Maximaximum** [comment]
@kristijanbambir hm, indeed! There are new versions on npm, even though the changelog contains no information about what changes these versions have.

**Comment by stevermeister** [comment]
sorry that I let you wait for such a long time, the update is coming - https://github.com/stevermeister/ngx-cookie-service/pull/111

**Comment by stevermeister** [comment]
**ngx-cookie-service@10.0.0** published

@kristijanbambir sorry for the confusion with CHANGELOG

**Comment by daiscog** [comment]
@stevermeister Thanks for the update.  Note that the peerDependencies on master are still incorrect: https://github.com/stevermeister/ngx-cookie-service/blob/master/projects/ngx-cookie-service/package.json#L74-L75

**Comment by stevermeister** [comment]
@daiscog thank you for pointing out 
**ngx-cookie-service@10.0.1**
