### ISSUE TITLE
Creating a cookie with only 1 of the optional paramters at the end of the entire params list forces the user to add all the parameters

### ISSUE THREAD

**Issue by Abhirup-2019** [stevermeister/ngx-cookie-service#105]
## Expected Behavior
...None

## Actual Behavior
...None

## Steps to Reproduce the Problem
... Suppose you want to add a param that is at the end of the list of optional params but for that you have to add all the params
in the list. This would be much better if you could have used interface overloading of some sorts where the user can just pick and choose, or even better if we can just pass an object with the parameters we want.

## Specifications

  - Version: ...
  - Browser: ...
  - ...

**Comment by robbiemu** [comment]
this is done: https://github.com/stevermeister/ngx-cookie-service/blob/4185244d25a8a060c9f6a48a69da02122ee8af56/projects/ngx-cookie-service/src/lib/cookie.service.ts#L105
could close this ticket
