### ISSUE TITLE
Changelog is not up-to-date

### ISSUE THREAD

**Issue by sebastianhaeni** [stevermeister/ngx-cookie-service#109]
## Expected Behavior
[CHANGELOG.md](https://github.com/stevermeister/ngx-cookie-service/blob/master/CHANGELOG.md) is referencing the latest version and lists the changes

## Actual Behavior
[CHANGELOG.md](https://github.com/stevermeister/ngx-cookie-service/blob/master/CHANGELOG.md)'s last version referenced is old

**Comment by zeusstl** [comment]
I installed from npm. The default was not SameSite="Lax", so I'm assuming I have an outdated version. Mentioning it here since it could be related to versioning as well.

**Comment by stevermeister** [comment]
@sebastianhaeni you are right, my bad. I will try to keep it up to date
