### ISSUE TITLE
Cookies Not Getting Set

### ISSUE THREAD

**Issue by alienjedi** [stevermeister/ngx-cookie-service#112]
## Expected Behavior
`set` function of ngx-cookie-service not working for Angular on Chrome Browsers

## Actual Behavior
The function  completed without giving any error. In the past, I was able to set cookies with the set functioin But after the new chrome 80 update, it was giving errors on the `SameSite` property not been set and users were unable to login to my site from updated chrome browsers. But even after setting the property, it still did not set the cookie. Also, I tried to set the path, domain and secure attributes just to be sure that it wasn't any of those that was causing the error. 
I also tried the work-around fix proposed in this [issue](https://github.com/stevermeister/ngx-cookie-service/issues/28) but it did not work as well.

## Steps to Reproduce the Problem
Implement a login flow and call the ngx-cookie-service `set` method when the log in button is clicked.
Then try retrieving the cookie using the ngx-cookie-service `get(cookieName: string)` function.
Or use the google chrome browser developer  tools to inspect if the cookie was set or not set.

## Specifications

Google Chrome Version 83.0.4103.116 (Official Build) (64-bit) On Linux
Google Chrome Version 84.0.4147.111 On Android version 7.1 Samsung Device
ngx-cookie-service: 2.4.0 installed via npm
Angular/compiler-cli: 8.2.14

**Comment by tuananhzippy** [comment]
I am also facing the same problem:

`this.cookieService.set('hello', 'world!');`
`alert(this.cookieService.get('hello'));`

**Not working with Chrome version 85.0.4183.83 (64 bit)**

**But it works fine with the Microsoft Edge browser**

**Comment by alienjedi** [comment]
I found a workaround. Check it out [here at medium](https://medium.com/better-programming/how-your-websites-and-apps-could-be-broken-right-now-by-the-chrome-80-update-b654f074313)

**Comment by alienjedi** [comment]
I now have a full understanding of why `ngx-cookie-service` was not correctly setting cookies for me.

-  `ngx-cookie-service` does not have an options based `set` method. 
   This means with the new Chrome 80 update which requires all cookies by default now be set with `SameSite=Lax`, if you decided to set the value explicitly rather than leave `ngx-cookie-service`  set it to `Lax`  for you or maybe you just decided to set it to some other value, then you must set the `Secure` property, `path` property and `domain` property altogether. This is because `ngx-cookie-service` does not allow optional values in the current set method.

   There is a [pull request](https://github.com/stevermeister/ngx-cookie-service/pull/114) to enable this feature but it has not been merged into the master branch yet.
   
   So, if you made a mistake of setting the `Secure` property to true and tested it in localhost, it wouldn't work. This is because the `Secure` property requires an https web server to set cookies, but your localhost is not https, it is http so Google Chrome rejects the cookie.

   See [this Medium story](https://medium.com/swlh/how-the-new-chrome-80-cookie-rule-samesite-none-secure-affects-web-development-c06380220ced) for more details 

-   So, to make things work fine again, I just updated to the latest version of the module which now sets `SameSite` property to `Lax` by default and I ignore all the other cookie properties after the `Expiry` property.

-   Going forward, avoid using Secure to set cookies when you are in Localhost.
