### ISSUE TITLE
Is 2.3.0 still the best version to use for Angular < 9 ?

### ISSUE THREAD

**Issue by raduanastase** [stevermeister/ngx-cookie-service#113]
There is a problem with cookie deletion on Chrome on Mac OS, and I want to know if there is a newer version I can use or if there is a possibility to do a PR for the 2.3.0 version?

**Comment by Dmitryp84** [comment]
@raduanastase I use Angular 8 with the latest ngx-cookie-service version. It looks like get/set/delete works fine. At least with "ng build --aot"

**Comment by raduanastase** [comment]
Did you try in Chrome on Mac OS?

**Comment by raduanastase** [comment]
> @raduanastase I use Angular 8 with the latest ngx-cookie-service version. It looks like get/set/delete works fine. At least with "ng build --aot"

If I build the plugin like this, will it work with the latest version? So I'm not stuck with 2.3.0?

**Comment by stevermeister** [comment]
@raduanastase 

>  is a possibility to do a PR for the 2.3.0 version?
is it still an issue for you? 
if yes - I can create separate branch for Angular < 9 and you can make PRs there and we will publish it
