### ISSUE TITLE
Safari/iOS no store/save cookies 

### ISSUE THREAD

**Issue by AlejandroFernandezUCAB** [stevermeister/ngx-cookie-service#115]
## Expected Behavior
 The cookies store/save

## Actual Behavior
The cookies not store/save, when I do this.cookie.get('item'), this return empty. 
This happen only in Safari/iOS

## Steps to Reproduce the Problem
``` 
console.log( this.cookie.get('item') );
```

## Specifications

  - Version: "ngx-cookie-service": "^3.0.4",
  - Browser: Safari 13.1.2
  - Angular 9
  - Ionic 5

**Comment by pedroct92** [comment]
As you are using angular 9 and probably using differential loading this article may help you: 

http://www.ilove-it.com/post/2019/08/28/safari-unauthorized-401-on-loading-angular-8-application-solved
