### ISSUE TITLE
Please support es5

### ISSUE THREAD

**Issue by kamcknig** [stevermeister/ngx-cookie-service#119]
## Expected Behavior
dev configuration builds of Angular should work in IE11. The installed module should ship with an es5 bundle that can be used in development configurations of angular apps

## Actual Behavior
Dev configuration builds error in development in IE11

## Steps to Reproduce the Problem
Create an angular project and set the tsconfig to target es5.
install the ngx-cookie-service module and use it in a component
run the development build of the angular app and open the page in IE 11 with development console open

Notice the syntax error 1002 in the console in the compiled vendor.js
![2020-11-27 10_06_18-Window](https://user-images.githubusercontent.com/705490/100462449-4bcfbd80-3098-11eb-923d-38ef9e216c5b.png)

## Specifications

  - Version: N/a
  - Browser: IE 11

**Comment by vishal4799** [comment]
@kamcknig 
do you know of any workaround so far?

**Comment by kyle-mcknight** [comment]
@vishal4799 No, fortunately, I can comment out the code where it is used as it's not a huge part of the application right now. Then I jus thope it works in production builds.

**Comment by kyle-mcknight** [comment]
https://github.com/exalif/angular-libs/issues/59#issuecomment-736716667

There is another library, ngx-mat-popover that has the same issue. Is there a way you can release a patch to an older version that does include es5? Or is there currently an older version that does?

**Comment by vishal4799** [comment]
@kamcknig, if your use case is simple enough, like mine where I just need to store a string value in a cookie and fetch it every time I launch the app then you can use the native javascript document object. Refer to the below link, hope it helps.

https://www.w3schools.com/js/tryit.asp?filename=tryjs_cookie_username

**Comment by stevermeister** [comment]
@kamcknig for IE11 support please use an old version of ngx-cookie-service.
Because we plan to migrate to 12 soon
