### ISSUE TITLE
Cookies dissapearing on page refresh and go back on next refresh

### ISSUE THREAD

**Issue by IgorKurkov** [stevermeister/ngx-cookie-service#120]
## Expected Behavior

Should work properly with browser cookies

## Actual Behavior

Cookies appear and disappear in each page refresh, without any idea. One injection of service, one "set cookie" function, it disappears, and on the next refresh, it appears, and again it disappears. No logic
 

## Specifications

  - Version: 8.2.3
  - Browser: Chrome latest 87.0.4280.88
  
  
  I know they're not so much information to research< I will try to create stackblitz. or can record video with dev-tools application tab. Only a thing - when I create a tiny service with my own methods to get/set cookies - they work as should. have no idea why `ngx-cookie-service` had this behavior.

**Comment by Diwakar14** [comment]
Unable to set cookie expiry, it automatically set the current time. 


var now = new Date();
              var time = now.getTime();
              var expireTime = time + (parseInt(expire) * 10000);

              if (this.cookie.check('auth_token')) {
                this.cookie.deleteAll();
              }
              this.cookie.set('auth_token', auth_token, new Date(expireTime), "http://localhost:4200", "localhost", true, "None");

**Comment by Portekoi** [comment]
Same behavior for me.

**Comment by IgorKurkov** [comment]
figured out this case by writing my own tiny cookieService. Hope it would be helpful while the issue willn't become resolved
```
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class CookieService {
  constructor() {}

  set(name: string, value: string, days: number): void {
    let expires = '';
    if (days) {
      const date = new Date();
      date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
      expires = '; expires=' + date.toUTCString();
    }
    document.cookie = name + '=' + (value || '') + expires + '; path=/';
  }

  get(name: string): string | null {
    const nameEQ = name + '=';
    const ca = document.cookie.split(';');
    // tslint:disable-next-line:prefer-for-of
    for (let i = 0; i < ca.length; i++) {
      let c = ca[i];
      // tslint:disable-next-line:triple-equals
      while (c.charAt(0) == ' ') c = c.substring(1, c.length);
      // tslint:disable-next-line:triple-equals
      if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
    }
    return null;
  }

  delete(name: string): void {
    document.cookie = name + '=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
  }
}

```

**Comment by stevermeister** [comment]
@IgorKurkov could you please create a sandbox for it?

**Comment by stevermeister** [comment]
@IgorKurkov I cannot reproduce your issue

here is a base example - https://github.com/stevermeister/ngx-cookie-service-base/blob/main/src/app/app.component.ts

executed on stackblitz - https://stackblitz.com/github/stevermeister/ngx-cookie-service-base?file=src%2Fapp%2Fapp.component.ts

pure app - https://rlmibppkj.github.stackblitz.io/
