### ISSUE TITLE
TypeError: get(name) method lacking null check

### ISSUE THREAD

**Issue by otaviopetry** [stevermeister/ngx-cookie-service#122]
Hello! I'm reporting an error that was caught by BugSnag in a project live version, after passing flawlessly by staging environment.

## Expected Behavior
Should check if **_result_** array has a position 1 before accessing it.

## Actual Behavior
_**result**_ is **null** in some cases, causing a TypeError: 

```
 get(name) {
    if (this.documentIsAccessible && this.check(name)) {
        name = encodeURIComponent(name);
        const regExp = this.getCookieRegExp(name);
        const result = regExp.exec(this.document.cookie);
        return this.safeDecodeURIComponent(result[1]);
    }
    else {
        return '';
    }
}
```

```
"TypeError Cannot read property '1' of null 
    node_modules/ngx-cookie-service/fesm2015/ngx-cookie-service.js:41:54 t.value"
```

## Steps to Reproduce the Problem
It's hard to say how to reproduce the problem, since it went error free all the way from development to live, passing by a staging environment (with BugSnag turned on aswell).

## Specifications

  - Version: _3.1.3_
  - Browser: _all 8 occurrences until now happened in Chrome, either Desktop or Mobile._
  - Angular: _10.1.6_

**Comment by stevermeister** [comment]
@otaviopetry thanks for reporting!

https://github.com/stevermeister/ngx-cookie-service/pull/123/files
