### ISSUE TITLE
Add the ability to publish new version to NPM when new tag published

### ISSUE THREAD

**Issue by pavankjadda** [stevermeister/ngx-cookie-service#136]
@stevermeister We should automate the process of publishing new version to NPM. Whenever new tag(release) created in Github, the CI should automatically create new version in NPM if not already exists. See this [example](https://github.com/ngxsmart/autocomplete/blob/master/.github/workflows/npm_publish.yml) and we should do the same for this project. Thoughts?

**Comment by pavankjadda** [comment]
@stevermeister  any update feedback on this?

**Comment by stevermeister** [comment]
sorry, for the late response, I was on vacation, and then flush my MFA and tried to restore access to the account.

> We should automate the process of publishing a new version to NPM. 

it would be awesome!

**Comment by jaddap2** [comment]
> sorry, for the late response, I was on vacation

No problem. Since you are Admin of the repo, you need to do couple of things

1. Create NPM token in https://npmjs.com. Example: https://www.npmjs.com/settings/jpavanaryan/tokens
2. Create GitHub secret and store that NPM token. See below for example

<img width="1907" alt="Screen Shot 2021-07-27 at 3 25 01 PM" src="https://user-images.githubusercontent.com/56288554/127215857-a5c98018-4ade-4c0f-a226-65c6fa09aa46.png">

**Comment by jaddap2** [comment]
@stevermeister I also created new [React library](https://github.com/ngxsmart/react-cookie-service) based on this. I use it in my project.

**Comment by stevermeister** [comment]
@jaddap2 I've created NPM_TOKEN secret

**Comment by pavankjadda** [comment]
> @jaddap2 I've created NPM_TOKEN secret
> 
> thank you for the instructions!

Thanks. I will create the Github action and try to deploy 12.0.1

**Comment by pavankjadda** [comment]
@stevermeister #141 implemented this. Closing the issue.

**Comment by stevermeister** [comment]
@pavankjadda do you know, will it still work if I setup MFA for npm? 

https://docs.npmjs.com/configuring-two-factor-authentication

**Comment by pavankjadda** [comment]
> @pavankjadda do you know, will it still work if I setup MFA for npm? 
> 
> 
> 
> https://docs.npmjs.com/configuring-two-factor-authentication

It should be. We can give it a try, enable it and I can change GitHub action to run on commit in `development` branch. 

Btw what timezone are you in? I am on US EST and typically available on 10 am later.

**Comment by stevermeister** [comment]
@pavankjadda I found that it was possible to do only for Auth, not for publishing. so all should still work. 

I'm in the Amsterdam time zone (UTC+2), so we have something like 7h difference
