### ISSUE TITLE
Version 12.0.1 issue

### ISSUE THREAD

**Issue by kambbado** [stevermeister/ngx-cookie-service#142]
## Expected Behavior
Should work, had to downgrade to version 12.0.0
## Actual Behavior
 Cannot find module 'ngx-cookie-service' or its corresponding type declarations

## Steps to Reproduce the Problem
Update to version 12.0.1
Run ng serve
## Specifications

- Version: .12.0.1
- Browser: N/A

**Comment by FedC** [comment]
Experienced the same

**Comment by pavankjadda** [comment]
@kambbado @FedC There is not much changed in 12.0.1. Let me check

**Comment by pavankjadda** [comment]
I believe this has to do with new node warning shown below. Will continue to investigate it.
 ```
 ⠋ Bundling to FESM2015(node:21363) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/jaddap2/WebstormProjects/ngx-cookie-service/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".

 ```

**Comment by jegjessing** [comment]
I too have problems. Looking in the folder, there is only an src folder and the "root" files no bundles or anything.
![image](https://user-images.githubusercontent.com/12476410/127727827-d2ad3f09-fd00-4ad3-892e-329a24eabb21.png)

**Comment by KevinQuinonesA** [comment]
I have the same problem, in my case it didn't work to go back to 12.0.0 version

**Comment by pavankjadda** [comment]
> I have the same problem, in my case it didn't work to go back to 12.0.0 version

Remove node_modules and do `npm install ngx-cooki-service@12.0.0`. It should fix the issue

**Comment by pavankjadda** [comment]
All, thanks for your comments and patients. 

> I too have problems. Looking in the folder, there is only an src folder and the "root" files no bundles or anything.
> ![image](https://user-images.githubusercontent.com/12476410/127727827-d2ad3f09-fd00-4ad3-892e-329a24eabb21.png)
> 
> Don't know if this helps, please let me know if I can help testing

You are right. I checked newly added GitHub action, it published incorrect directory. It is fixed it now.

@kambbado @jegjessing @FedC @KevinQuinonesA please try now, version `12.0.2` should fix the issue.

**Comment by rlesavre** [comment]
This fixes it for me, thanks
