### ISSUE TITLE
Github issue templates are not working

### ISSUE THREAD

**Issue by pavankjadda** [stevermeister/ngx-cookie-service#149]
Github issue templates are not working #149

**Comment by pavankjadda** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by pavankjadda** [comment]
@stevermeister I added Github issue templates few days, it seems they are not working. I don't have access to configure them. When you get a chance please configure them. You see the detailed instructions here https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by stevermeister** [comment]
nice idea! 
added, please check

**Comment by pavankjadda** [comment]
Thanks. Looks good

**Comment by pavankjadda** [comment]
> nice idea!
> added, please check

Thanks, looks good. I also created Discord channel for the project and updated `README.md` with link. Both Angular and React communities use Discord. So I think it would be helpful for folks to share and discuss issues.
