### ISSUE TITLE
Refactor setCookie method to reduce complexity?

### ISSUE THREAD

**Issue by pavankjadda** [stevermeister/ngx-cookie-service#154]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

@stevermeister should we refactor `setCookie` method and reduce complexity? At present it follows recursion to determine cookie options. I think we can refactor it and make it simple. I did this for[ react-cookie-service ](https://github.com/ngxsmart/react-cookie-service/blob/master/libs/react-cookie-service/src/lib/useCookies.tsx#L120)library which you can see [here](https://github.com/ngxsmart/react-cookie-service/blob/master/libs/react-cookie-service/src/lib/useCookies.tsx#L120). Let me know your thoughts.

### Describe alternatives you've considered

NA

**Comment by stevermeister** [comment]
@pavankjadda sorry, not sure what exactly do you want to refactor. could you elaborate on this, please? 
do you mean remove polymorphism like in react-cookie-service? when the function has only one interface

**Comment by pavankjadda** [comment]
> do you mean remove polymorphism like in react-cookie-service? when the function has only one interface

Yes, the reason I say that is because we can simplify it without recursion and pass options directly instead of passing again. I think it's redundant to build options object and call it again.

**Comment by pavankjadda** [comment]
Never mind, I think we can leave it as is for now.
