### ISSUE TITLE
Support cookies.onChanged

### ISSUE THREAD

**Issue by JGhignatti** [stevermeister/ngx-cookie-service#159]
Hi,

I'd like to discuss the possibility of supporting `cookies.onChanged` (documentation found [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged)) in this library. The service could wrap it and expose an Observable that components and other services could listen to.
Is it something that the lib could favor on? Is it something that the maintainers would support for the lib?

If so, I'd like to submit a PR (that I've not started yet, I'd like to get a positive from the maintainers) adding this new feature and we can discuss the implementation here or once I create the PR with the proposed solution.
If the maintainers would prefer for them to work on it, that's ok as well.

Thank you all.

**Comment by pavankjadda** [comment]
@JGhignatti This is something I thought of few days ago. But the real question is why? Do you have any use case(s) that would need this functionality? And also Safari does not support this feature and it's not ideal to implement something that is not supported by all browsers.

<img width="1096" alt="Screen Shot 2021-08-12 at 4 54 26 PM" src="https://user-images.githubusercontent.com/56288554/129268481-b77ec522-1607-4305-b3b9-784dbd081a14.png">


@stevermeister thoughts?

**Comment by JGhignatti** [comment]
Thanks for answering.

The use case I first had in mind is best solved with a refresh token, but could also be solved by listening to the cookie expiring and acting on it. I understand this may not be a good solution, so no, I don't think I have a use case.

Also, I saw that Safari didn't support it, but I didn't think it was a big deal. You are right, makes no sense to implement this feature if the developers using the lib would have to write workarounds for the Safari browser.
