### ISSUE TITLE
Code Scanning Alert: Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by pavankjadda** [stevermeister/ngx-cookie-service#160]
### Describe the bug

Github Code Scanning shows following [high severity alert](https://github.com/stevermeister/ngx-cookie-service/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster). **Incomplete string escaping or encoding**

### Steps to Reproduce

See the alert here https://github.com/stevermeister/ngx-cookie-service/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://github.com/stevermeister/ngx-cookie-service/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster

### Expected behaviour

The alert should not exist

### What version of the library you see this issue?

12.0.3

### What version of Angular are you using?

Angular 12

**Comment by pavankjadda** [comment]
> I see the alert.
> but do you see an issue here?

According to the alert **This does not escape backslash characters in the input**. So my question is if cookie has slash characters, will it work? If it does, we can close the alert as False Positive.

**Comment by stevermeister** [comment]
just checked in the console - it works. 
not sure about specification, but I believe it's possible

**Comment by pavankjadda** [comment]
> just checked in the console - it works. 
> 
> not sure about specification, but I believe it's possible

Okay. I am gonna close the issue and alert. We can open it back if we get the error in future.
