### ISSUE TITLE
@stevermeister I created [sample repo](https://github.com/pavankjadda/angular-ssr-docker) that demonstrates this. Clone the project and run as per instructions in Readme.md file

### ISSUE THREAD

**Issue by deba10106** [stevermeister/ngx-cookie-service#181]
@stevermeister I created [sample repo](https://github.com/pavankjadda/angular-ssr-docker) that demonstrates this. Clone the project and run as per instructions in Readme.md file

_Originally posted by @pavankjadda in https://github.com/stevermeister/ngx-cookie-service/issues/1#issuecomment-939225082_

I tried your code. But I get "Cannot read property 'getHeader' of null"

**Comment by pavankjadda** [comment]
@deba10106 this is still being tested. I will let you as soon as it's ready. Then you can test and give us feedback.
