### ISSUE TITLE
How to get Server's cookie in Front End

### ISSUE THREAD

**Issue by astechnolabs-html** [stevermeister/ngx-cookie-service#197]
### Describe the bug

Hi,

I am using latest version of iONIC. and I am trying to login using frappe framework APIs.

Now, Frappe generates Session ID on server side, and set it in server's **Response header -> Set-Cookie**

I want to access that "Set-Cookies" in front-side, as it contains session ID.

here is a screenshot what I want to access.

![image](https://user-images.githubusercontent.com/74809936/142916223-2b60860f-7d02-49c6-9c80-70e311b5986c.png)

### Steps to Reproduce

-

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

-

### Expected behaviour

-

### What version of the library you see this issue?

Current

### What version of Angular are you using?

Angular 11

### Screenshots

![image](https://user-images.githubusercontent.com/74809936/142916526-402c38c8-8bfc-416f-b81e-972a587c8875.png)

**Comment by pavankjadda** [comment]
@astechnolabs-html when server returns cookies with `Set-Cookie`, the browser adds them automatically. You don't have to set them. If you still want to access, use `get()` method after browser sets them
