### ISSUE TITLE
SSR reverted

### ISSUE THREAD

**Issue by MaticDiba** [stevermeister/ngx-cookie-service#207]
### Describe the bug

Support for SSR seems reverted in newer versions. Is there any plan to implement it again?

### Steps to Reproduce

Using:
`"ngx-cookie-service": "^13.1.2",`

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

/

### Expected behaviour

/

### What version of the library you see this issue?

/

### What version of Angular are you using?

Angular 13

**Comment by pavankjadda** [comment]
@MaticDiba we are discussing the best way to implement this. It will be back soon.

**Comment by MaticDiba** [comment]
Greate. Looking forward to it.
