### ISSUE TITLE
Namespace '"/Users/p21-0008/Desktop/Dushyant/Demo/Angular CRUD With Authentication/frontend/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

### ISSUE THREAD

**Issue by CodeIntelli** [stevermeister/ngx-cookie-service#243]
### Describe the bug

We are using ngx-cookie-service in Our Angular Project But facing this issue after installing this package
![Screenshot 2022-07-23 at 12 23 59 PM](https://user-images.githubusercontent.com/68110141/180594164-35bcf2ba-a679-417c-854f-9b29176fa904.png)
e

package.json FIle 

`{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.4",
    "@angular/common": "~10.2.4",
    "@angular/compiler": "~10.2.4",
    "@angular/core": "~10.2.4",
    "@angular/forms": "~10.2.4",
    "@angular/localize": "~10.2.4",
    "@angular/platform-browser": "~10.2.4",
    "@angular/platform-browser-dynamic": "~10.2.4",
    "@angular/router": "~10.2.4",
    "@ng-bootstrap/ng-bootstrap": "^8.0.4",
    "bootstrap": "^4.5.0",
    "ngx-cookie-service": "^13.2.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular/cli": "~10.2.1",
    "@angular/compiler-cli": "~10.2.4",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
`

### Steps to Reproduce

Not able to find the solution regarding this 

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

Due to some confidential issue not able to share the project more information 

### Expected behaviour

Cookies is not working Facing Issue at angular application run time.

### What version of the library you see this issue?

14.0.1,13.2.1

### What version of Angular are you using?

Angular 10

**Comment by pavankjadda** [comment]
If you are using Angular version 10, then you need to use `ngx-cookie-service` version 12.x.x or below.
```
npm i ngx-cookie-service@12.0.--save
```
