### ISSUE TITLE
ngx-cookie-service-ssr  is it possible to use this in angular V10? 

### ISSUE THREAD

**Issue by CodeIntelli** [stevermeister/ngx-cookie-service#244]
### Is your feature request related to a problem? Please describe

When we are using ngx-cookie-service it will not be working in Server Side rendering as you mentioned in your Readme.md, if we want to use this library in SSR we need to add one more library and when I install this library it shows a warning log like

![Screenshot 2022-07-26 at 4 32 14 PM](https://user-images.githubusercontent.com/68110141/180991156-4159281c-6edd-4768-bf4f-22f9e8e1623c.png)
 
 
 Can you provide me more details regarding this?

### Describe the solution you'd like

To work this library in angular 8+ version with SSR Support.

### Describe alternatives you've considered

Not using any alternative

**Comment by pavankjadda** [comment]
@CodeIntelli it was designed to use Angular 14 or later. But it should work in v10 with the warning you see.

**Comment by CodeIntelli** [comment]
Hey @pavankjadda, first of all, thanks for your response. Here I have used this package but it's not working in SSR

**Comment by pavankjadda** [comment]
> Hey @pavankjadda, first of all, thanks for your response. Here I have used this package but it's not working in SSR

What part not working? Do you see any error?

**Comment by CodeIntelli** [comment]
I want to load the whole page response from the server and I have completed this (without authorization) API Endpoint but the main difference is that in many APIs which will be required a token to authorize the request at that time i am sending token using cookie but it show undefined. means the token is not able to send to the server. But when i am dealing with Client Side Rendering It will be working properly.

**Comment by pavankjadda** [comment]
> I want to load the whole page response from the server and I have completed this (without authorization) API Endpoint but the main difference is that in many APIs which will be required a token to authorize the request at that time i am sending token using cookie but it show undefined. means the token is not able to send to the server. But when i am dealing with Client Side Rendering It will be working properly.

Could you share a sample repo that reproduces that issue? I am unable to reproduce it.

**Comment by CodeIntelli** [comment]
I have sorted the issue. now i can get the token from angular server using Express request and store token from this library 

@pavankjadda Thanks for your Support
