### ISSUE TITLE
Ability to set a global/default domain for set and delete

### ISSUE THREAD

**Issue by sagrawal31** [stevermeister/ngx-cookie-service#245]
### Is your feature request related to a problem? Please describe

As of now, to use the `cookieService.set` or `cookieService.delete`, we have to always pass a custom parent domain which has 3 different values based on 3 different environments.

### Describe the solution you'd like

To overcome this problem, we can provide a injector token to set a default value for the domain.an

### Describe alternatives you've considered

- **1st alternative** - I'll raise a PR (as my time permits) because this is a simple feature.
- **2nd alternative**- I'll extend the `CookieService` and replace the provider.

### Additional context

My angular app and backend API runs on two different subdomains under one domain so I have to set the cookie domain to my parent domain. So thought of raising this issue.

**Comment by pavankjadda** [comment]
@sagrawal31 If possible send a PR, we will take a look.

**Comment by sagrawal31** [comment]
Apolgoies, @pavankjadda. Didn't get a chance so far. I can spend time in the first week of April if that's acceptable.

**Comment by pavankjadda** [comment]
Okay. I am closing this for now. Create PR when you are ready
