### ISSUE TITLE
ngx-cookie-service does not work on Angular 12 with Ivy Compiler

### ISSUE THREAD

**Issue by dgates82** [stevermeister/ngx-cookie-service#255]
### Describe the bug

When attempting to use ngx-cookie-service with Angular 12 it produces compiler errors:
![image](https://user-images.githubusercontent.com/48529034/206279824-795f6246-9dcc-4345-917b-87a32b06e905.png)

This is when using either version 12.0.3 or 13.2.1 of the ngx-cookie-service

### Steps to Reproduce

npm i ngx-cookie-service@12.0.3

Import CookieService in app.module.ts 
![image](https://user-images.githubusercontent.com/48529034/206280150-a89495a9-1f36-4cf6-986e-0577ca134375.png)

ng build

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

Pending

### Expected behaviour

ngx-cookie-service version 12 should be compatible with angular 12 with ivy enabled since that is now the default compiler and View Engine is no longer supported

### What version of the library you see this issue?

12.0.3

### What version of Angular are you using?

Angular 12

**Comment by pavankjadda** [comment]
@dgates82 can you send us reproducible repo in StackBlitz?

**Comment by dgates82** [comment]
@pavankjadda , I'll try to reproduce in StackBlitz this evening and send over the link

**Comment by dgates82** [comment]
@pavankjadda , here is the link to the StackBlitz with the error. 
https://stackblitz.com/edit/angular-ivy-zd6j17?file=package.json,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

Thanks

**Comment by pavankjadda** [comment]
> @pavankjadda , here is the link to the StackBlitz with the error. https://stackblitz.com/edit/angular-ivy-zd6j17?file=package.json,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
> 
> Thanks

You should provide `CookieService` under `providers`


```
@NgModule({
  imports: [BrowserModule, FormsModule],
  declarations: [AppComponent, HelloComponent],
  bootstrap: [AppComponent],
  providers: [CookieService],
})
export class AppModule {}
```
