### ISSUE TITLE
Get raw cookies value

### ISSUE THREAD

**Issue by GaetanRouzies** [stevermeister/ngx-cookie-service#279]
### Is your feature request related to a problem? Please describe

When working on SSR i often need to send the cookies received by the Express server (SSR) to the API to get User Context in the Server Side Generated Html.

To do this i'm explicitly adding the cookie Header to the request in the interceptor. 
The problem is that i need the "raw cookies value" in the following format : _field1=value1; field2=value2_.

I would like to use directly the cookieService instead of using the @Inject(REQUEST). So for the moment here's what i'm doing.

```typescript
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
  if (this.platformService.isPlatformServer()) {
    req = req.clone({
      withCredentials: true,
      headers: new HttpHeaders({ cookie: getHeaderString(this.cookieService.getAll()) })
    });
  } else {
    req = req.clone({ withCredentials: true });
  }
  return next.handle(req);
}

function getHeaderString(obj: object): string {
  return Object.entries(obj)
    .map(([key, value]) => `${key}=${value}`)
    .join('; ');
}
```

### Describe the solution you'd like

I would like to add a function getRawCookieValue() in the SsrCookieService and/or CookieService which will return the raw "cookie" value.

```typescript
getRawCookieValue(): string {
  return this.documentIsAccessible ? this.document?.cookie : this.request?.headers.cookie;
}
```

So i can use the following code

```typescript
intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
  if (this.platformService.isPlatformServer()) {
    req = req.clone({
      withCredentials: true,
      headers: new HttpHeaders({ cookie: this.cookieService.getRawCookieValue() })
    });
  } else {
    req = req.clone({ withCredentials: true });
  }
  return next.handle(req);
}
```

### Describe alternatives you've considered

Alternatives solutions without adding this function. 
- Using directly the injected Request object to access this.request.headers.cookie.
- Using the getHeaderString function below to format back from .getAll() to raw cookie value.

```
function getHeaderString(obj: object): string {
  return Object.entries(obj)
    .map(([key, value]) => `${key}=${value}`)
    .join('; ');
}
```

**Comment by pavankjadda** [comment]
@GaetanRouzies you can use `document.cookie` to get raw cookies. We use same to set cookies.
