### ISSUE TITLE
Get expiry date

### ISSUE THREAD

**Issue by Soolan** [stevermeister/ngx-cookie-service#281]
### Is your feature request related to a problem? Please describe

Using:
set( name: string, value: string, options?: { expires?: number | Date, path?: string, domain?: string, secure?: boolean, sameSite?: 'Lax' | 'None' | 'Strict'}): void;

you can set the expiry date for a cookie.

But I can't find any function to read the expiry date associated with a cookie. 

### Describe the solution you'd like

na

### Describe alternatives you've considered

na

**Comment by pavankjadda** [comment]
@Soolan What would be usecase for this?

**Comment by Soolan** [comment]
@pavankjadda a few days ago I was facing a challenge where I was asked to refresh a cookie expiry time based on another timestamp variable.

Turned out that other timestamp object would be redundant IF we would be able to read the expiry time from the cookie itself. 
Just a thought.

**Comment by pavankjadda** [comment]
@Soolan Unfortunately the browser do not expose cookie expiration date. They only return cookie value.
