### ISSUE TITLE
TS2307: Cannot find module  @angular/ssr/tokens  or its corresponding type declarations.

### ISSUE THREAD

**Issue by pavankjadda** [stevermeister/ngx-cookie-service#283]
### Describe the bug

Angular 170.0.0-rc.0 sows error `TS2307: Cannot find module  @angular/ssr/tokens  or its corresponding type declarations` in SsrCookieService

### Steps to Reproduce

Clone v17 branch

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

NA

### Expected behaviour

Work as expected

### What version of the library you see this issue?

17.0.0-rc.0

### What version of Angular are you using?

Angular 13

**Comment by pavankjadda** [comment]
Upstream issue https://github.com/angular/angular-cli/issues/26110

**Comment by pavankjadda** [comment]
Fixed in #287

**Comment by its-dibo** [comment]
> Fixed in #287

I installed the latest version of @angular/ssr which is v17.0.7, but I couldn't find `REQUEST` in it, is it available in other place?

**Comment by pavankjadda** [comment]
> > Fixed in #287
> 
> I installed the latest version of @angular/ssr which is v17.0.7, but I couldn't find `REQUEST` in it, is it available in other place?

Use version 17.0.1
