### ISSUE TITLE
Support Angular 16

### ISSUE THREAD

**Issue by tsteuwer-accesso** [stevermeister/ngx-cookie-service#285]
### Is your feature request related to a problem? Please describe

You cannot install this dependency without `--force` because of the peer dependency stuck at `^15.0.0`.

### Describe the solution you'd like

 You could instead use `>=15.0.0` and that would resolve the issue.

### Describe alternatives you've considered

The only one you can use is `npm i --force`.

**Comment by pavankjadda** [comment]
> ### Is your feature request related to a problem? Please describe
> You cannot install this dependency without `--force` because of the peer dependency stuck at `^15.0.0`.
> 
> ### Describe the solution you'd like
> You could instead use `>=15.0.0` and that would resolve the issue.
> 
> ### Describe alternatives you've considered
> The only one you can use is `npm i --force`.
> 
> ### Additional context
> _No response_

You can use 
```
npm i ngx-cookie-service@15.0.0
```

**Comment by tsteuwer-accesso** [comment]
@pavankjadda , we have 15 installed locally but you will get an error due to the peerDependency angular because it's using `^15.0.0`

```
 "peerDependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0"
  },
```
Shouldn't that be `>=15.0.0`

**Comment by pavankjadda** [comment]
> @pavankjadda , we have 15 installed locally but you will get an error due to the peerDependency angular because it's using `^15.0.0`
> 
> ```
>  "peerDependencies": {
>     "@angular/common": "^15.0.0",
>     "@angular/core": "^15.0.0"
>   },
> ```
> 
> Shouldn't that be `>=15.0.0`? `^15.0.0` means you can use it with any version of Angular 15.

I don't understand the question. For v16 use
```
npm i ngx-cookie-service
```

and for v15
```
npm i ngx-cookie-service@15.0.0
```
