### ISSUE TITLE
Angular v17 SSR - InjectionToken for REQUEST/RESPONSE not working?

### ISSUE THREAD

**Issue by Shamshiel** [stevermeister/ngx-cookie-service#292]
Either I'm doing something wrong or cookies can't be retrieved from request headers via the SsrCookieService. It seems that SsrCookieService is not able to retrieve the request from the providers.

I have the server.ts and my guard like described below but the bearer token can't be retrieved. I checked the incoming request in the server and the cookie is available in the header. So I assume the request is for some reason not correctly provided to the SsrCookieService.

Is that a bug or am I doing something wrong?

## `server.ts`
```
server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [
          { provide: APP_BASE_HREF, useValue: baseUrl },
          { provide: 'REQUEST', useValue: req },
          { provide: 'RESPONSE', useValue: res },
        ],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });
```

## Guard
```
export function authenticationGuard(): CanActivateFn {
    return () => {
        const authService: AuthService = inject(AuthService);
        const router: Router = inject(Router);
        const cookieService: SsrCookieService = inject(SsrCookieService);

        return authService.getUser().pipe(
            map((x) => {
                const bearerToken = cookieService.get('access_token');
                console.log('Bearer Token: ' + bearerToken);
                if (x.role !== 'admin') {
                    router.navigate(['/home']);
                    return false;
                }
                return true;
            })
        );
    };
}
```

## Specifications

- Version: Angular 17.0.0 and ngx-cookie-service-ssr 17.0.0

**Comment by jnizet** [comment]
I think the issue is that the code uses a non-exported `REQUEST` InjectionToken, so providing the request under the string token `'REQUEST'` won't work to populate it.

**Comment by pavankjadda** [comment]
@Shamshiel Can you share stackblitz reproduction?

**Comment by pavankjadda** [comment]
@Shamshiel create new issue by following issue template and stackblitz reproduction

**Comment by oriollpz** [comment]
Any news in this problem? I can't access my cookies in the SSR of Angular 17.

**Comment by pavankjadda** [comment]
> Any news in this problem? I can't access my cookies in the SSR of Angular 17.

No. I am able to access them in my code. Can you share an example where you can't access them?

**Comment by oriollpz** [comment]
When you use a Guard and try to access the cookie when does SSR, it returns null the "req" Injection.

**Comment by zozjo** [comment]
Any news in this problem

**Comment by pavankjadda** [comment]
@oriollpz @zozjo Can anyone of you try share a StackBlitz example of tis problem?

**Comment by xalidevxx** [comment]
> Fixed in version `17.0.1`

Hi! I am facing the same error. 

I am using: 
`
"@angular/ssr":"~17.0.0",
"ngx-cookie-service-ssr": "^17.0.1"
`

I did 
`
console.log(this.cookieService.get('lang')) 
`
and got:
![Screenshot from 2023-12-25 00-39-54](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/89d67337-b883-4a02-86e5-d854e43430e6)
![Screenshot from 2023-12-25 00-37-55](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/f35cea58-d41f-488c-bedf-1af44d6d9712)
![Screenshot from 2023-12-25 00-37-14](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/81fdac90-bdab-43a3-b697-3cc0e097e40f)
![Screenshot from 2023-12-25 00-43-17](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/fa35efd1-09f7-456b-b4ba-a5c504d76b28)

- server side: "undefined"
- client side: "ru"

Can you help me please. I have attached the screenshots.

![Screenshot from 2023-12-25 00-39-54](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/89d67337-b883-4a02-86e5-d854e43430e6)

![Screenshot from 2023-12-25 00-37-55](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/f35cea58-d41f-488c-bedf-1af44d6d9712)

![Screenshot from 2023-12-25 00-37-14](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/81fdac90-bdab-43a3-b697-3cc0e097e40f)

![Screenshot from 2023-12-25 00-43-17](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/fa35efd1-09f7-456b-b4ba-a5c504d76b28)

**Comment by pavankjadda** [comment]
@xalidevxx See updated docs https://github.com/stevermeister/ngx-cookie-service?tab=readme-ov-file#server-side-rendering. You need to import `REQUEST`

**Comment by xalidevxx** [comment]
> @xalidevxx See updated docs https://github.com/stevermeister/ngx-cookie-service?tab=readme-ov-file#server-side-rendering. You need to import `REQUEST`

Ohhhhh yessssss, thank you:))))

**Comment by xalidevxx** [comment]
> @xalidevxx See updated docs https://github.com/stevermeister/ngx-cookie-service?tab=readme-ov-file#server-side-rendering. You need to import `REQUEST`

I added the request as in the documentation. Then I built the project and ran the production version locally. I output cookieService.get('lang') in app.component.html. 

As a result:
- there is no cookie on the server side
- on the client side there is a cookie. 

**Is this how it should work?**


![Screenshot from 2023-12-25 12-59-18](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/e9372ab2-b3a1-4024-adde-9491f0594d1d)

![Screenshot from 2023-12-25 13-01-16](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/a4a52113-40bf-41fb-b044-aeafaa609074)

![Screenshot from 2023-12-25 13-05-15](https://github.com/stevermeister/ngx-cookie-service/assets/65123079/74792130-4540-4f9b-8e8f-7a3511f85429)

**Comment by xalidevxx** [comment]
> @xalidevxx See updated docs https://github.com/stevermeister/ngx-cookie-service?tab=readme-ov-file#server-side-rendering. You need to import `REQUEST`

Hi! Can you help me please?

**Comment by davpirelli** [comment]
News about this issue? Still got same behaviour on latest release

**Comment by xalidevxx** [comment]
> News about this issue? Still got same behaviour on latest release

Hi! I didn't find a solution and left it like that.

**Comment by pavankjadda** [comment]
All, I am looking at this. Stay tuned.

**Comment by rhutchison** [comment]
Might be related https://github.com/angular/angular-cli/issues/26323

**Comment by ydang204** [comment]
is there any news guys? I'm facing the same issue

**Comment by cskiwi** [comment]
Stumbled upon this issue as well. would be amazing to have it fixed :)

**Comment by humanely** [comment]
Any fixes yet?

**Comment by BenasPal** [comment]
Guys issue is related to https://github.com/angular/angular-cli/issues/28535, while running ng serve it wont work unless in angular v19. You need to npm run build:ssr and then npm run serve:ssr. Also make sure you provide request` { provide: REQUEST, useValue: req },`  with `import { REQUEST } from 'ngx-cookie-service-ssr';`

**Comment by Clashsoft** [comment]
In newer versions you need to import REQUEST from @angular/core.
