### ISSUE TITLE
Support for partitioned property for CHIPS

### ISSUE THREAD

**Issue by screambeard** [stevermeister/ngx-cookie-service#301]
### Is your feature request related to a problem? Please describe

The problem is that Google Chrome is rolling out blocking of third-party cookies. One of the cases for third-party cookies is an iframe embed another domain. One of the solutions is using Partitioned cookies. See Google Documentation for more detail: https://developers.google.com/privacy-sandbox/3pcd/chips

### Describe the solution you'd like

The set function should include a way to set the Partitioned property. I would propose to extend the interface like this:

```
set( name: string, value: string, expires?: number | Date, path?: string, domain?: string, secure?: boolean, sameSite?: 'Lax' | 'Strict' | 'None', partitioned?: boolean): void;
```

and

```
set( name: string, value: string, options?: { expires?: number | Date, path?: string, domain?: string, secure?: boolean, sameSite?: 'Lax' | 'None' | 'Strict', partitioned?: boolean}): void;
```

The extension of the function itself should be straightforward, something like this:

```
if (options.partitioned) {
      cookieString += 'Partitioned;';
}
```

### Describe alternatives you've considered

Creating the cookie without the service.

**Comment by pavankjadda** [comment]
@screambeard I will take a look

**Comment by pavankjadda** [comment]
@screambeard try version` 17.1.0-rc.1`
