### ISSUE TITLE
'"ngx-cookie-service-ssr"' has no exported member named 'CookieService'. Did you mean 'SsrCookieService'?ts(2724)

### ISSUE THREAD

**Issue by cyberiumchain** [stevermeister/ngx-cookie-service#306]
### Describe the bug

The documentation says that user -ssr only for ssr. But the CookieService is not available in -ssr.

### Steps to Reproduce

import { CookieService } from 'ngx-cookie-service-ssr';

### Please provide a link to a minimal reproduction of the bug. StackBlitz, CodePen or CodeSanBox

https://angular-ivy-ehmvey.stackblitz.io

### Expected behaviour

As per Readme, importing the ngx-cookie-service-ssr should be enough. 

### What version of the library you see this issue?

17

### What version of Angular are you using?

Angular 13

### Desktop? Please complete the following information

MACOS

**Comment by pavankjadda** [comment]
You have to install `ngx-cookie-service-ssr` not `ngx-cookie-service`

**Comment by swcm-mnestler** [comment]
@pavankjadda the readme is still inaccurate, the exported class of `ngx-cookie-service-ssr` is called `SsrCookieService` not `CookieService`.

**Comment by pavankjadda** [comment]
> @pavankjadda the readme is still inaccurate, the exported class of `ngx-cookie-service-ssr` is called `SsrCookieService` not `CookieService`.

Where do you see this?
