### ISSUE TITLE
Will the "HttpOnly" parameter be added

### ISSUE THREAD

**Issue by N1K0D4** [stevermeister/ngx-cookie-service#313]
### Is your feature request related to a problem? Please describe

It is standard for cookies.

### Describe the solution you'd like

Just add this parameter to the list of parameters.

### Describe alternatives you've considered

It is not possible to add third-party entries, as there is a strict binding to the parameters. There is no free field.

**Comment by pavankjadda** [comment]
@N1K0D4 HttpOnly cookies can only be set and can not be read by JavaScript. But we can add an option to set it
