### ISSUE TITLE
[Angular 18] `ngx-cookie-service-ssr` `get` returns empty string even if cookie is available

### ISSUE THREAD

**Issue by apappas1129** [stevermeister/ngx-cookie-service#326]
### Describe the bug

It seems that this service inherits the same issue reported [here](https://github.com/angular/angular-cli/issues/26323) where Angular 18's `ng serve` is [not using `server.ts`](https://github.com/angular/angular-cli/issues/26323#issuecomment-1805808114) which means that adding the providers ` { provide: SSR_REQUEST, useValue: req }` and `{ provide: 'RESPONSE', useValue: res }` won't serve its [purpose](https://github.com/stevermeister/ngx-cookie-service/blob/d6c916be034e49667d43da9d3fd2299cd2e32eff/projects/ngx-cookie-service-ssr/src/lib/ssr-cookie.service.ts#L86). 

I tried building and serving the `dist/<project>/server/server.mjs` and it did get the existing cookie successfully.

### Steps to Reproduce

1. Use Angular 18
2. install ngx-cookie-service-ssr and follow instructions in readme regarding adding of the providers in the express server
3. `ng serve` and test `.get` method (make sure cookie exists)

### Expected behaviour

1. should work with ng serve
2. should work seemlessly on the client and ssr runtime

### What version of the library you see this issue?

"ngx-cookie-service-ssr": "^18.0.0"

### What version of Angular are you using?

Angular 18

**Comment by apappas1129** [comment]
I wanted to try out the v19 pre-release and do a simple `ng update @angular/cli @angular/core --next=true` which should install the angular versioned `19.0.0-next.9`. But I get a Migration failed because 
> ` Package "ngx-cookie-service-ssr" has an incompatible peer dependency to "@angular/ssr" (requires "^18.0.0-next.2", would install "19.0.0-next.9").`

**Comment by apappas1129** [comment]
Upgrading to v19 pre-release solved the issue. _ATTOW_, `ng update @angular/cli @angular/core --next=true --force` pulled in version `19.0.0-next.9` and `ng serve` now successfully "provides" the `providers` defined in the `server.ts` CommonEngine.render`.

**Comment by pavankjadda** [comment]
> Upgrading to v19 pre-release solved the issue. _ATTOW_, `ng update @angular/cli @angular/core --next=true --force` pulled in version `19.0.0-next.9` and `ng serve` now successfully "provides" the `providers` defined in the `server.ts` `CommonEngine.render`.

Closing as per this
