### ISSUE TITLE
URI malformed error for cookie value of '20%'

### ISSUE THREAD

**Issue by simeyla** [stevermeister/ngx-cookie-service#54]
## Expected Behavior
* I don't expect any errors when parsing existing cookies (eg. with a value of `20%`)

## Scenario
* I am developing a new website. Users of the existing website have existing cookies already set.
* Currently a cookie containing the exact value `20%` has been set by the old website
* No I don't mean `%20` !
* I get an error just trying to run `getAll()`

## Actual Behavior
I get `URI malformed` because `decodeURIComponent('20%')` fails 

## Steps to Reproduce the Problem
* Set cookie value of `20%` 
* Try to execute `getAll()`

## Specifications

  - Version: 2.1.0
  - Browser: Chrome

**Comment by CunningFatalist** [comment]
Hello,

yes, I guess that's a bug. I haven't tested it yet, but it makes sense. I will fix this as soon as I have some time. Sadly, I don't know when this is going to be yet. Thanks for reporting this issue.

Cheers

**Comment by NarasimhaA-Hexaware** [comment]
I am also facing the same issue, ampersand(&) replaced by %26 value. 
I set the cookie value TEST&123&223 in code, but in a browser, cookie value replaced by TEST%26123526223. Due to this bug, I could not able to complete my task. Please fix soon
`

**Comment by gauravdeshmukh612** [comment]
can anyone please  accept this pull request ASAP ?

**Comment by SimonCropp** [comment]
just closing the loop. work has stopped on this project and it is looking for new maintainers https://github.com/7leads/ngx-cookie-service#warning-announcement-new-maintainer-needed

**Comment by codingbadger** [comment]
![image](https://user-images.githubusercontent.com/1089628/73834376-8152a400-4803-11ea-9336-c836f065b845.png)
