### ISSUE TITLE
The Cookie is not Set when passing a Value of Days

### ISSUE THREAD

**Issue by vicmarcal** [stevermeister/ngx-cookie-service#75]
## Expected Behavior
When executing:
 this.cookieService.set( 'Test', 'Hello World', 4 );
It's expected to have a Cookie set by ngx-cookie-services

## Actual Behavior
No Cookie is set.
However a Cookie is set if:
this.cookieService.set( 'Test', 'Hello World')

## Steps to Reproduce the Problem
Nothing special. Just copy the line and execute it.

## Specifications

  - Version: ngx-cookie-service 2.2.0
  - Browser: Google Chrome 
  - Angular 7
  - Executed in Localhost

**Comment by bgever** [comment]
I can reproduce this issue in version 1.0.10, Chrome and Angular 8.

**Comment by l-Legacy-l** [comment]
Looking for a fix to this issue

Anyone has a solution ?

**Comment by SimonCropp** [comment]
just closing the loop. work has stopped on this project and it is looking for new maintainers https://github.com/7leads/ngx-cookie-service#warning-announcement-new-maintainer-needed

**Comment by codingbadger** [comment]
![image](https://user-images.githubusercontent.com/1089628/73834398-8879b200-4803-11ea-93c2-bc8642058852.png)

**Comment by stevermeister** [comment]
@vicmarcal is it still actual?
