### ISSUE TITLE
Cookie not being set in Chrome versions < 60 with ngx-cookie-service 2.3.0

### ISSUE THREAD

**Issue by avadhootha** [stevermeister/ngx-cookie-service#80]
## Expected Behavior
Using ngx-cookie-service 2.3.0, when a cookie is being set with key, value, expiry and path, Chrome browser should set the cookies in all browsers. 
this.cookieService.set('NAME_APP', 'NAME', 1, '/');
## Actual Behavior
No cookie is being set in the chrome browsers with version < 57. 

## Reason 
With the ngx-cookie-service v> 1.0.10, the code introduced the new attribute Samesite and set the default value as None. Older browsers(< chrome 60) reject the Samesite value as None without the secure flag. So this causes the browser to ignore the cookie value and fails in the applications using latest version of cookieservie. We were able to figure out this issue when we bumped up the version from 1.0.10 to 2.3.0.  A link which explains the same why Samesite default value should be Lax instead. https://web.dev/samesite-cookies-explained/
https://www.chromium.org/updates/same-site/incompatible-clients

## Steps to Reproduce the Problem
You can open browser stack and open any version lesser than chrome v60 in windows 10.
You can try the following command in console.

document.cookie= 'NAME_APP=NAME;expires=Sat, 01 Feb 2020 17:39:19 GMT;path=/;sameSite=None;' 
document.cookie= 'NAME_APP2=NAME2;expires=Sat, 01 Feb 2020 17:39:19 GMT;path=/;sameSite=Lax;' 
You will notice that only the second cookie is being set. 

## Specifications

  - Version: < v60
  - Browser: Chrome

## Workaround
For the users who are using ngx-cookie-service and using > v1.0.10, please set the cookie with Samesite attribute **Lax** or **Strict** explicitly or **None**(along with secure flag as well). Until the ngx-cookieService does a fix to set the default value as Lax or (None with secure) the above solution works fine for all browsers.

**Comment by Yohandah** [comment]
I believe this should be fixed by #79 .... :/ have the same warning
