### ISSUE TITLE
Wrap the other optional parameter to an interface like CookieOptions to avoid passing all unset parameters

### ISSUE THREAD

**Issue by rsarmiento-pl** [stevermeister/ngx-cookie-service#90]
## Expected Behavior
Pass and wrap all the optional parameter as an object, this will ease the usage of setting a cookie with few optional parameters. 

```
export interface CookieOptions {
 expires?: number | Date; 
 path?: string; 
 domain?: string;
 secure?: boolean;
 sameSite?: 'Lax' | 'Strict' | 'None';
}

// Usage
let options: CookieOptions  = {expires: 123,sameSite: 'None' };
this._cookieService.set(key, value, options);
```

## Actual Behavior
`this._cookieService.set(key, value, 123, undefined, undefined, undefined, 'None');`

**Comment by minijus** [comment]
I would like to take this.

@stevermeister do you have any thoughts on this before I start?

**Comment by stevermeister** [comment]
@minijus could you make it polymorphic, please? (to support old format for some time)

**Comment by minijus** [comment]
> @minijus could you make it polymorphic, please? (to support old format for some time)

yes, absolutely. The idea is to have overloads.
