### ISSUE TITLE
Delete not working

### ISSUE THREAD

**Issue by chrisstpierre** [stevermeister/ngx-cookie-service#93]
## Expected Behavior
```javascript
    this.cookieService.set('Test', 'Hello World');
    console.log(this.cookieService.getAll());
    this.cookieService.delete('Test');
    this.cookieService.delete('Test', '/');
    this.cookieService.delete('Test', '/', 'localhost');
    console.log(console.log(this.cookieService.getAll()));
```

```
{Test: "Hello World"}
{}
```
cookie is deleted

## Actual Behavior
```javascript
    this.cookieService.set('Test', 'Hello World');
    console.log(this.cookieService.getAll());
    this.cookieService.delete('Test');
    this.cookieService.delete('Test', '/');
    this.cookieService.delete('Test', '/', 'localhost');
    console.log(console.log(this.cookieService.getAll())); 
```
```
{Test: "Hello World"}
{Test: "Hello World"}
```
cookie is not deleted
## Steps to Reproduce the Problem
...

## Specifications

  - Version: 3.0.2
  - Browser: chrome

**Comment by truong-phan** [comment]
Hi, take a lock this link, maybe will help you resolve the problem
https://github.com/stevermeister/ngx-cookie-service/pull/92/files
For me, i changed my code to this.cookieService.delete(key, options.path, options.domain, false, 'Lax');

**Comment by piaro** [comment]
Same problem.

@truong-phan Thank you for your information.
Did you mean we have to set `domain`, `secure`, `sameSite` fully?

**Comment by truong-phan** [comment]
Hi @piaro , yes, try to set sameSite, because sameSite default = 'None', maybe different sameSite in your browser, f12 and check your sameSite.

**Comment by piaro** [comment]
@truong-phan completely understood, thank you! :)))

**Comment by Withnail73** [comment]
Hey there.  I'm seeing the same issue suddenly (worked 2 days ago) but I'm on 2.3.0 running in Chrome... Angular 8.

**Comment by brandontulsi** [comment]
This open PR seems to fix the issue: https://github.com/stevermeister/ngx-cookie-service/pull/91

**Comment by dmytrodemchenko** [comment]
I have the same issue with delete/deleteAll methods - still exist even with the 3.0.3 version.

**Comment by chrisstpierre** [comment]
3.0.3 fixed the issue described here

**Comment by saad14092** [comment]
The issue is still relevant for me with 3.0.4

**Comment by pavankjadda** [comment]
I am using Angular 9.1.x and I have this issue

**Comment by dmytrodemchenko** [comment]
Hey, Guys
The same as the above comment. Still not always removable in Angular 9+ via your plugin. 
Reproducible with sub-domains functionality.

**Comment by pavankjadda** [comment]
To delete a cookie we are setting cookie value like this
```
X-Auth-Token=;expires=Thu, 01 Jan 1970 00:00:01 GMT;path=/;sameSite=Lax;
```
at this [line](https://github.com/stevermeister/ngx-cookie-service/blob/405b47cdfce8f0f06e1ca526c3e6b795f2a74f0a/projects/ngx-cookie-service/src/lib/cookie.service.ts#L137) and it's causing the issue.

**Comment by webcourse-ng** [comment]
It looks like I've the same issue as dmytrodemchenko: on a subdomain, the cookie that gets set is prefixed with a dot: `.sub.domain.com.` Delete doesn't work on it. If I rename the cookie to remove the leading dot and re-run the delete, it clears just fine.

**Comment by webcourse-ng** [comment]
Work around: instead of trying to delete the cookie, set it again with an expired date. That's how delete is coded to work - it just gets applied to the wrong domain when in a subdomain.

`set('panda_cookie', '', new Date('Thu, 01 Jan 1970 00:00:01 GMT'), '/', 'domain', true, 'None')`

**Comment by stevermeister** [comment]
for new version of ngx-cookie-service delete functionality should work.
if it does not work for you - please provide a test spec for it.

**Comment by abhishek75** [comment]
> Hey there. I'm seeing the same issue suddenly (worked 2 days ago) but I'm on 2.3.0 running in Chrome... Angular 8.

@here you can use the set method to delete the cookies.

this.cookieService.set(
name_of_the_cookie_tobe_deleted,
'',
-1,
path,
domain_name,
use_existing_value,
use_existing_value
);

    The key is to set the same name cookie with value === '' and date as expiration date or -1
    
    I hope this works.

**Comment by TheVirtuoso27** [comment]
async logout(){
    await new Promise((resolve, reject) => {
      try{
        this.cookieService.delete('SessionLoged','/')
        this.cookieService.delete('DataLoged','/')
        resolve(true)
      }
      catch(err){
        reject(false)
      }

    }).then(() => {
      this.router.navigateByUrl('/login')
    })
  }``

**Comment by TheVirtuoso27** [comment]
`async logout(){
    await new Promise((resolve, reject) => {
      try{
        this.cookieService.delete('SessionLoged','/')
        this.cookieService.delete('DataLoged','/')
        resolve(true)
      }
      catch(err){
        reject(false)
      }

    }).then(() => {
      this.router.navigateByUrl('/login')
    })
  }`

**Comment by chintuyadavsara** [comment]
I am still facing the issue with delete and deleteAll in my localhost.
Sometimes Its working, sometimes not. Tried Many ways, but none worked for me.

**Comment by mymo689** [comment]
I have the delete method not working issue happening for me as well, running cookie-service 12.0.3 with Angular 12.1.3. Seems to be completely random, I can't find a common denominator for steps to reproduce reliably.

**Comment by tmalysz** [comment]
Apparently, I have the same trouble with deleting. Using 3.1.3, because of having older angular version.
Delete on localhost does work, but on further environments `.delete()` does not have any effect. Tried with no arguments and with full list of ones matching the list visible in browser dev tools.
